name: CI for instaui-mermaid
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


env:
  NPM_DIR_NAME: npm-mermaid

jobs:
  testing:
    name: testing web app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-suffix: py${{ matrix.python-version }}

      - name: set up npm-mermaid
        uses: instaui-python/org-ci-config/.github/actions/npm-env@main
        with:
          npm_dir_name : ${{ env.NPM_DIR_NAME }}
          test_cmd: ""

      - name: set up python and playwright and install the project
        uses: instaui-python/org-ci-config/.github/actions/playwright-python-env@main

      - name: run web tests
        timeout-minutes: 2
        run: |
          uv run --python python --no-dev pytest __tests/testing_web
        shell: bash
